### ISSUE TITLE
How do we run hunspell within LaMachine?

### ISSUE THREAD

**Issue by willstout** [proycon/LaMachine#102]
I know it's installed, but I don't see any commands that run it.

**Comment by proycon** [comment]
LaMachine currently only installs hunspell if you enable installation of gecco (as it's a dependency for that), otherwise it doesn't. It's not enabled by default.

**Comment by proycon** [comment]
(The command, once installed, is ``hunspell``)

**Comment by proycon** [comment]
Ah sorry, I see what's wrong. LaMachine currently only installs the hunspell *library*, not the command line tool, they are in separate packages on most distributions and gecco technically only needs the library so that's why it's missing. You're best off simply installing the hunspell package yourself ( ``sudo apt-get install hunspell``) if you want a quick fix, but I'll add it to LaMachine as part of the gecco installation too.

You indeed don't need to use gecco if you just want hunspell, that would be overkill.

**Comment by proycon** [comment]
(should be fixed in latest release)

**Comment by proycon** [comment]
Definitely, mea culpa, the package should be ``hunspell-de-de`` for debian/ubuntu. I'll adapt it.

**Comment by proycon** [comment]
Should be fixed now in v2.2.11 (let's hope for the best ;) )
