### ISSUE TITLE
ERROR! failed to combine variables, expected dicts but got a 'dict' and a 'AnsibleSequence':

### ISSUE THREAD

**Issue by eduarddrenth** [proycon/LaMachine#128]
Perhaps related to https://github.com/ansible/ansible/issues/43259

[lamachine-oersetter.log](https://github.com/proycon/LaMachine/files/2699046/lamachine-oersetter.log)

**Comment by eduarddrenth** [comment]
related to #19 ?

**Comment by proycon** [comment]
No, that issue was on LaMachine v1 which didn't use ansible yet. It does seem something is wrong with the installation manifest (``install.yml``). I would expect it to say "hosts: localhost" instead of "hosts: all" (which is set by https://github.com/proycon/LaMachine/blob/master/bootstrap.sh#L1414). The fact that it doesn't might be the cause of this error.

I'd suggest deleting the ``lamachine-controller/`` directory and ``install*yml`` file, in the dir you run the bootstrap from. You can also pass ``--install oersetter`` to the bootstrap script to save you the effort from having to edit it manually in the editor.

**Comment by eduarddrenth** [comment]
allright....again clearing, let you know

**Comment by eduarddrenth** [comment]
build geslaagd....misschien dit issue sluiten, maar...

Als je probeert via de config paketten uit te zetten loop je al gauw tegen deze zeer cryptische melding op. Wellicht is dat wat te verbeteren.
