### ISSUE TITLE
pycrypto fails to build: clang does not know gmp.h

### ISSUE THREAD

**Issue by antalvdb** [proycon/LaMachine#130]
[lamachine-stable-20181231_143356.log](https://github.com/proycon/LaMachine/files/2718443/lamachine-stable-20181231_143356.log)

**Comment by proycon** [comment]
Hmm, I figure pycrypto is usually grabbed from a binary wheel package instead of compiled from source. Our regular tests on macOS show no problem. Can you try a ``brew install gmp`` prior to LaMachine update? That should provide the necessary headers. I may need to add it to LaMachine if this issue is something new more people stumble accross.

**Comment by antalvdb** [comment]
gmp is already installed according to brew --
Warning: gmp 6.1.2_2 is already installed and up-to-date

LaMachine update error remains the same

**Comment by proycon** [comment]
You got it working after all?

**Comment by antalvdb** [comment]
It worked from the commandline:

env "CFLAGS=-I/usr/local/include -L/usr/local/lib" pip install pycrypto

See:

https://stackoverflow.com/questions/15375171/pycrypto-install-fatal-error-gmp-h-file-not-found
