### ISSUE TITLE
ImportError on ucto when updating

### ISSUE THREAD

**Issue by EdwinWenink** [proycon/LaMachine#145]
I had a working LaMachine installation on my Arch Linux system, but my installation stopped working. My kernel is: 5.0.13-arch1-1-ARCH. When updating (also with the force options), I consistently receive the following error:

```
Running: python3 -c 'import ucto'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /home/edwin/lama/lib/libucto.so.3: undefined symbol: _ZN5folia15AllowCorrection7correctERKSt6vectorIPNS_12FoliaElementESaIS3_EES7_S7_S7_RKSt3mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESE_St4lessISE_ESaISt4pairIKSE_SE_EEE
```

**Comment by proycon** [comment]
I have come across this problem myself as well (also on Arch). Arch being a rolling release, it often happens that stuff in LaMachine breaks after an update because it needs to be recompiled (a simple ``lamachine-update force=1``). Somehow something goes wrong with the python bindings. I actually thought I had solved it with the last v2.6.2 release but if you encountered it again (with force=1 and even force=2) then I didn't succeed and have to look deeper. 

You don't have one of our AUR packages installed which might possibly cause a conflict? (``pacman -Qq | grep folia``)

**Comment by proycon** [comment]
I just did an upgrade from 2.5.1 to 2.6.3 which went fine on Arch. Hopefully I can reproduce it soon (I'm expecting a new big libfolia/frog/ucto release this week which might trigger the problem again and give another opportunity to solve it)

**Comment by EdwinWenink** [comment]
I did not have that package installed, but indeed your recent update already fixed it! My error log was already a few days old, my bad! Before that I had the same problem for over a week, and I didn't realize there was an update so recent.  Thanks for the effort.

**Comment by proycon** [comment]
Ah, glad to hear that! Then it worked after all :)
