### ISSUE TITLE
Can't find a usable init.tcl

### ISSUE THREAD

**Issue by Irishx** [proycon/LaMachine#176]
when running ' colibri-loglikelihood -help '   on lamachine-stable on ponyland, i got the following error:

application-specific initialization failed: Can't find a usable init.tcl in the following directories: 
    /usr/share/tcltk/tcl8.6 /usr/lib/tcl8.6 /lib/tcl8.6 /usr/library /library /tcl8.6.1/library /tcl8.6.1/library

/usr/share/tcltk/tcl8.6/init.tcl: version conflict for package "Tcl": have 8.6.1, need exactly 8.6.8
version conflict for package "Tcl": have 8.6.1, need exactly 8.6.8
    while executing
"package require -exact Tcl 8.6.8"
    (file "/usr/share/tcltk/tcl8.6/init.tcl" line 19)
    invoked from within
"source /usr/share/tcltk/tcl8.6/init.tcl"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list source $tclfile]"

This probably means that Tcl wasn't installed properly.

**Comment by proycon** [comment]
I doubt this is related to colibri, because there's no dependencies at all in that. The only thing in LaMachine that could cause such an error is Alpino. But I don't understand why that would pop up now.

**Comment by proycon** [comment]
Ok, I finally found out what caused this. The issue occurs as soon as bash is invoked. Bash sources something called ``modules`` (which I had never heard of) via ``/etc/profile.d/modules.sh`` . This in turn indeed loads something that is written in Tcl.

However, because Alpino ships its own Tcl and LaMachine uses that (set in LD_LIBRARY_PATH), there is a mismatch and this warning occurs.

I can't yet seem to find a good way to disable this ``modules`` functionality unfortunately, as it's something that's installed globally (on ponyland) and sourced by all bash instances.

**Comment by proycon** [comment]
On ponyland, this should now be fixed due to a patch the system administrators applies to ``/etc/profile.d/modules.sh``
