### ISSUE TITLE
Virtualenv-bootstrap virtualenv/pip not found

### ISSUE THREAD

**Issue by JeroenSteen** [proycon/LaMachine#29]
I'm trying to run LaMachine in a CentOS 7 LXC container.
I cloned LaMachine and runned `./virtualenv-bootstrap.sh python2`,
but I get `No suitable package manage detected`, `virtualenv not found` and `pip3 or pip not found`. I have virtualenv and pip installed, and I can run those commands in the terminal. Do I have to do something extra?

**Comment by proycon** [comment]
Interesting, I hadn't tried to run inside an LXC container yet myself, I wonder if some of the errors are due to this? The ``No suitable package manage detected`` means it can't find ``yum``, which seems a bit odd. What does ``which yum`` say in your container? Do ``virtualenv`` and ``pip`` work from within the container too?

Could you attach your log file if the error persists?

By the way, the ``python2`` support is limited and not as well tested, normal Python 3 is recommended if possible.

**Comment by JeroenSteen** [comment]
In the container I have Python 2.7.5.
I also installed Epel via yum install epel-release (I saw this error: `Unable to install EPEL repository!`).
`Which` returns for yum, virtualenv and pip:
```
/usr/bin/yum
/usr/bin/virtualenv
/usr/bin/pip
```
I think LaMachine can't find these, because of sudo (`sudo: command not found`).
`yum install sudo` in the container confirms that.

The previous time I used LaMachine I had `python2`, maybe I have to check how to upgrade then.

**Comment by proycon** [comment]
Right, LaMachine's ``virtualenv-bootstrap.sh`` contains two stages, a global installation stage in which it calls ``yum`` to install dependencies, and a compilation/installation stage for most of our own software. It will install python 3 for you by default as well (through EPEL on CentOS)

If you install ``sudo`` in your container and ensure that the user you use has rights to actually use ``sudo`` (i.e. is in ``/etc/sudoers``) then things should work.

**Comment by proycon** [comment]
Issue expired, closing, please reopen if still relevant.
